### PR TITLE
Update README to correct last name

### PR DESCRIPTION
**Pull request by TheMellyBee**

### CODE REVIEW

**Comment by Arctem** [comment]
You just want to have the last commit to the repo, don't you? :P

**Comment by DesignedByMel** [comment]
How did you know?! ;) Although only fair since I didn’t contribute from October on apparently. haha Man I was a lazy butt.
 



 	
Melanie Burns
about.me/melanieburns



 <https://about.me/melanieburns?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

 	
Melanie Burns
about.me/melanieburns
 <https://about.me/melanieburns?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by Arctem** [comment]
I think that's only because of rebases collapsing your commits into other ones.

**Comment by DesignedByMel** [comment]
Yeah I realize that. Which is totally fine. Just joking with ya. Thanks!

**Comment by izzycecil** [comment]
*Wakes up at 2AM*
"OH MY GOD, THE NAME WAS WRONG!" 
;)

**Comment by Arctem** [comment]
"GUESS I'VE GOTTA GO BACK AND FAIL ALL OF THEM"

**Comment by DesignedByMel** [comment]
It's the little things 😜 Who is gonna notice the unfinished compiler with the name correct!?! 🙄 haha how was Iceland?

**Comment by DesignedByMel** [comment]
😱

**Pull request merged**
